### ISSUE TITLE
Repo base64 encoding is correct, the spec example is wrong

### ISSUE THREAD

**Issue by ralfonso-directnic** [Paginar/gppstring#2]
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/issues/8

**Comment by bgazzera** [comment]
Thanks @ralfonso-directnic for creating a ticket here, but we are in the process of deprecating this library in favor of IAB's own. You can find it here: https://github.com/IABTechLab/iabgpp-es
